Added notice for Neve Pro in the page builder module
Codeinwp/themeisle-companion pull request #718
Opened 2021-12-13 20:09 UTC by arinaturcu

If Neve is active and the user is not pro, a notice is added in the Page Builder module's description.

[Codeinwp/neve-pro-addon#1741](https://github.com/Codeinwp/neve-pro-addon/issues/1741)

2021-12-14 16:08 UTC, cristian-ungureanu requested changes

2021-12-14 16:08 UTC, cristian-ungureanu commented on obfx_modules/beaver-widgets/init.php
> +			$this->description .= '<div class="neve-pro-notice"><p>You can get access to <b>10+ more Elementor and Gutenberg widgets</b>, including Instagram integration, display conditions and more in <b>Nev
@arinaturcu There are two modules named Page builder widgets. This one only appears when Beaver builder is active. As we don't have something dedicated for Beaver in Neve PRO, we should not add the notice here.
You can find the other one in `obfx_modules/elementor-widgets`.

Also, when you add this notice there, please make sure that the strings can be translated. You can use `sprintf` function when the string is combined with HTML code.

2021-12-20 12:05 UTC, cristian-ungureanu requested changes
Thank you for the changes @arinaturcu, just a little change is required and then we can move this to the testing column.

2021-12-20 12:05 UTC, cristian-ungureanu commented on obfx_modules/elementor-widgets/init.php
> +						. sprintf( __( 'You can get access to %1$s10+ more Elementor and Gutenberg widgets%2$s, including Instagram integration, display conditions and more in %3$sNeve PRO%4$s.', 'themeisle-companion'
@arinaturcu, I think it's better to combine the strings like this so when translation happens, they won't have parameters in the ending results that are replaced just by HTML tags. Also, the `Neve PRO` string doesn't need a translation.

```
sprintf(
		__( 'You can get access to %1$s, including Instagram integration, display conditions and more in %2$s.', 'themeisle-companion' ).
		sprintf( '<b>%1$s</b>',
			__( '10+ more Elementor and Gutenberg widgets', 'themeisle-companion' ),
		),
		'<b>Neve PRO</b>'
		);
```

2021-12-22 09:32 UTC, cristian-ungureanu approved these changes

2021-12-22 09:33 UTC, cristian-ungureanu commented
Looks good! Thank you @arinaturcu 🚀

2021-12-22 15:06 UTC, irinelenache commented
@arinaturcu Tested this PR and didn't find any problem 🚀 Will move it to **Ready to merge**

2021-12-22 15:12 UTC, merged